services:
  angular:
    build:
      dockerfile: tools/Docker/angular/Dockerfile
    network_mode: host
    ports:
      - 4200:4200
    user: ${DOCKER_USER:? (to fix) export DOCKER_USER="$(id -u):$(id -g)")}
