# for visualization use vscode:Preview Swagger
openapi: 3.1.0
info:
  title: Free Library Admin
  description: Admin REST API
  version: 0.0.0

security:
  # TODO optional use of admin credentials
  #- {
  #   type: apiKey,
  #   name: api_key,
  #   in: header
  # }

servers:
  - url: https://192.168.4.1/api # android needs absolute IP

paths:
  /catalog/{path}/?lock:
    parameters:
      - name: path
        in: path
        required: false
        schema: { type: string }
    put:
      summary: set the folder to admin only access
      responses:
        "200": { description: OK }
        "403": { description: Permission Denied }
        "404": { description: Folder Not Found }
        "429": { description: Client should try again }
    delete:
      summary: set the folder to open access
      responses:
        "200": { description: OK }
        "403": { description: Permission Denied }
        "404": { description: Folder Not Found }
        "429": { description: Client should try again }
