# for visualization use vscode:Preview Swagger
openapi: 3.1.0
info:
  title: Free Library
  description: Catalog REST API
  version: 0.0.0

security:
  - {}  # allow unsecured access

servers:
  - url: http://192.168.4.1/api # android needs absolute IP

paths:
  /firmware:
    get:
      summary: firmware version info
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  version: { type: string, description: firmware version }
                  hardware: { type: string, description: hardware type }
        "429": { description: Client should try again }
    put:
      summary: update firmware
      requestBody: { application/octet-stream: {} }
      responses:
        "200": { description: OK }
        "429": { description: Client should try again }
