# for visualization use vscode:Preview Swagger
openapi: 3.1.0
info:
  title: Sneakernet Firmware
  description: Firmware REST API
  version: 0.0.0

security:
  - {}  # allow unsecured access, as firmware is signed

servers:
  - url: http://192.168.4.1/api # android needs absolute IP

paths:
  /firmware:
    get:
      summary: firmware info
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:  { type: string, description: "firmware version" }
                  hardware: { type: string, description: "hardware type" }
    put:
      summary: update firmware
      description: "new firmware must later than current"
      requestBody: { application/octet-stream: {} }
      responses:
        "200": { description: OK }
        "403": { description: FAIL }
