openapi: 3.0.0
info:
  title: SneakerNet
  description: REST API for SneakerNet
  version: 0.0.0

paths:
  /catalog:
    get:
      summary: Catalog of UIDs [Publisher][Content]
      responses:
        '200':
          description: OK
          content:
            applicaction/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    platform_uid:
                      description: public key of publisher
                      type: integer
                    content_uids:
                      type: array
                      items:
                        description: checksum of content
                        type: integer

  /catalog/{publisher}/{content}:
    parameters:
      - name: publisher
        description: publisher's UID
        in: path
        required: true
        schema:
          type: integer
      - name: content
        description: content's UID
        in: path
        required: true
        schema:
          type: integer

    get:
      summary: Download EPUB3 ebook
      responses:
        '200':
          description: content
          content:
            application/epub+zip: {}

    put:
      summary: Add content
      requestBody:
        required: true
        content:
          application/epub+zip: {}
      responses:
        '403':
          description: Librarian doesn't accept Publisher UID
        '406':
          description: epub book failed checks
        '415':
          description: epub format not supported
        '507':
          description: no more storage available on node

  /catalog/{publisher}:
    parameters:
      - name: publisher
        description: publisher's UID
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Publisher Info
      responses:
        '200':
          description: content
          content:
            application/xml:
              schema:
                $ref: 'http://www.w3.org/2000/09/xmldsig'

