openapi: 3.0.0
info:
  title: SneakerNet
  description: REST API for SneakerNet
  version: 0.0.0

servers:
  - url: http://192.168.1.1

paths:
  /catalog:
    get:
      summary: Catalog of {PublisherUUID:[ContentUUID]}
      responses:
        '200':
          description: OK
          content:
            applicaction/json:
              schema:
                type: object


  /ebooks/{publisherUuid}/{contentUuid}:
    parameters:
      - name: publisherUuid
        description: publisher's UUID
        in: path
        required: true
        schema:
          type: string
      - name: contentUuid
        description: content's UUID
        in: path
        required: true
        schema:
          type: string

    get:
      summary: Download EPUB3 ebook
      responses:
        '200':
          description: content
          content:
            application/epub+zip: {}

    put:
      summary: Add content
      requestBody:
        required: true
        content:
          application/epub+zip: {}
      responses:
        '403':
          description: Librarian doesn't accept Publisher
        '406':
          description: epub book failed checks
        '415':
          description: epub format not supported
        '507':
          description: no more storage available on node

  /publishers/{publisher}:
    parameters:
      - name: publisher
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Publisher Info
      responses:
        '200':
          description: content
          content:
            application/xml:
              # schema:
              #   $ref: 'http://www.w3.org/2000/09/xmldsig'

