openapi: 3.0.0
info:
  title: SneakerNet Librarian
  description: REST API for SneakerNet Librarian
  version: 0.0.0

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

    BearerAuth:
      type: http
      scheme: bearer

    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

paths:
  /publisher/{publisher}:
    parameters:
      - name: publisher
        required: true
        in: path
        schema:
          type: integer
    put:
      summary: Add Publisher
      responses:
        '507':
          description: no more storage available on node
    delete:
      summary: Remove Publisher
      responses:
        '200':
          description: OK

# TODO change password
# TODO transfer ownership