openapi: 3.0.0
info:
  title: SneakerNet
  description: REST API for SneakerNet
  version: 0.0.0

# no security required
security: []

servers: []

paths:
  api/catalog:
    get:
      description: Returns a list of content
      responses:
        '200':
          description: Successfully returned a list of content
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - filename
                    - size
                  properties:
                    filename:
                      type: string
                    size:
                      type: integer
                    timestamp:
                      type: integer
        '404':
          description: catalog not ready
        '429':
          description: Too Many Requests

  api/catalog/{filename}:
    parameters:
      - name: filename
        in: path
        required: true
        schema:
          type: string
    get:
      description: receive the file
      responses:
        '200':
          description: transferring file
          content:
             application/octet-stream: {}
        '404':
          description: Not Found
        '429':
          description: Too Many Requests
    put:
      description: add file
      requestBody:
        content:
          # must set HTTP:Content-Length
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: accepted file
        '411':
          description: Content-Length required
        '429':
          description: Too Many Requests
    delete:
      description: remove file
      responses:
        '200':
          description: file was removed
        '404':
          description: File Not Found

  api/firmware:
    get:
      description: Returns current firmware info
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                required:
                  - filename
                  - version
                properties:
                  filename:
                    type: string
                  version:
                    type: string
        '500':
          description: invalid firmware
    put:
      description: update the firmware
      requestBody:
        content:
          # must set HTTP:Content-Length
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: accepted update, rebooting...
        '400':
          description: firmware was rejected
