openapi: 3.0.0
info:
  title: SneakerNet Librarian
  description: REST API for SneakerNet Librarian
  version: 0.0.0

servers:
  - url: https://192.168.4.1

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

# use http basic auth for all access
security:
  - BasicAuth: []

paths:
  /password:
    put:
      description: Change the password
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: New password accepted
        '500':
          description: node not able to set the new password



