openapi: 3.1.0
info:
  title: SneakerNet
  description: REST API
  version: 1.0.0

servers:
  - url: http://192.168.4.1/api
    description: user interface

paths:
  /catalog_contents:
    get:
      description: used for synchronization - provides a current listing of all folders/files
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: key is the path to the folder/file
                additionalProperties:
                  $ref: "#/components/schemas/CatalogEntry"
                  description: each Entry is either a folder or file
        "429": { description: "Client should try again" }

  /catalog/{folder}/:
    description: access to a catalog folder
    parameters:
      - name: folder
        in: path
        schema: { type: string }
        required: true
        description: an empty value will access the catalog root
    get:
      description: list folder content (subfolders and files)
      responses:
        "200":
          description: OK
          content:
            application/json:
              { schema: { $ref: "#/components/schemas/CatalogEntry" } }
        "429": { description: "Client should try again" }
        "404": { description: "Folder Not Found" }
    put:
      description: create subfolder
      responses:
        "200": { description: "OK" }
        "401": { description: "Unauthorized" }
        "404": { description: "Parent Folder Not Found" }
        "429": { description: "Client should try again" }
    post:
      description: change the 'icon' for the folder
      parameters:
        - in: query
          name: icon
          required: true
          schema:
            {
              type: boolean,
              description: "if supplied assumes the user is uploading an image",
            }
        - in: header
          name: Content-Length
          required: true
          schema: { type: integer, description: "size in bytes of the icon" }
      requestBody:
        content:
          image/*: {}
      responses:
        "200": { description: "OK" }
        "401": { description: "Unauthorized" }
        "412": { description: "Content-Length not provided" }
        "413": { description: "Payload Too Large" }
        "429": { description: "Client should try again" }
    delete:
      description: remove subfolder
      responses:
        "200": { description: "OK" }
        "401": { description: "Unauthorized" }
        "404": { description: "Folder Not Found" }
        "409": { description: "Folder Not Empty" }
        "429": { description: "Client should try again" }

  /catalog/{folder}/{file}:
    description: access to catalog content (files)
    parameters:
      - name: folder
        in: path
        schema: { type: string }
        required: true
      - name: file
        in: path
        schema: { type: string }
        required: true
    get:
      description: download the file
      responses:
        "200":
          description: "OK"
          content: { application/octet-stream: {} }
        "404": { description: "File Not Found" }
        "429": { description: "Client should try again" }
    put:
      description: add a file to the catalog
      parameters:
        - in: header
          name: Content-Length
          required: true
          schema: { type: integer, description: "size in bytes" }
        - in: query
          name: title
          required: false
          schema: { type: string, description: "pretty title for file" }
      requestBody:
        content: { application/octet-stream: {} }
      responses:
        "200": { description: "OK" }
        "401": { description: "Unauthorized" }
        "412": { description: "Content-Length not provided" }
        "413": { description: "Payload Too Large" }
        "429": { description: "Client should try again" }
    delete:
      description: remove the file
      responses:
        "200": { description: "OK" }
        "401": { description: "Unauthorized" }
        "404": { description: "File Not Found" }
        "429": { description: "Client should try again" }


  /catalog_title/{folder}/{file}:
    parameters:
      - name: folder
        in: path
        schema: { type: string }
        required: true
      - name: file
        in: path
        schema: { type: string }
        required: true
    put:
      description: set the title for the file
      parameters:
        - in: query
          name: title
          schema: { type: string }
      responses:
        "200": { description: "OK" }
        "401": { description: "Unauthorized" }
        "404": { description: "File Not Found" }
        "429": { description: "Client should try again" }


  /catalog_icon/{folder}/{file}:
    parameters:
      - name: folder
        in: path
        schema: { type: string }
        required: true
      - name: file
        in: path
        schema: { type: string }
        required: true
    put:
      description: set the icon for the file
      parameters:
        - in: header
          name: Content-Length
          required: true
          schema: { type: integer, description: "size in bytes" }
      requestBody:
        content: { image/*: {} }
      responses:
        "200": { description: "OK" }
        "401": { description: "Unauthorized" }
        "404": { description: "File Not Found" }
        "429": { description: "Client should try again" }

components:
  schemas:
    CatalogEntry:
      description: key is the name of the file or folder
      oneOf:
        - $ref: "#/components/schemas/FolderEntry"
        - $ref: "#/components/schemas/FileEntry"
      discriminator:
        propertyName: isFolder
        mapping:
          true: "#/components/schemas/FolderEntry"
          false: "#/components/schemas/FileEntry"

    FolderEntry:
      type: object
      required:
        - isFolder
      properties:
        isFolder: { type: boolean }
        isLocked:
          { type: boolean, description: "true if admin controls this folder" }
        hasIcon: { type: boolean, "true if entry has a custom icon" }

    FileEntry:
      type: object
      required:
        - isFolder
        - size
        - timestamp
      properties:
        isFolder: { type: boolean }
        size: { type: integer, description: "size of the file in bytes" }
        timestamp: { $ref: '#/components/schemas/timestamp' }
        title: { type: string }
        isLocked:
          { type: boolean, description: "true if admin controls this folder" }
        hasIcon: { type: boolean, "true if entry has a custom icon" }

    timestamp:
      type: string
      description: "ISO 8601 Z"
