openapi: 3.0.0
info:
  title: SneakerNet
  description: REST API for SneakerNet
  version: 0.0.0

# no security required
security: []

servers: [
  # android doesn't resolve (needs absolute IP)
  url: http://192.168.4.1/api
]

paths:
  /catalog:
    get:
      description: Returns a list of content
      responses:
        '200':
          description: Successfully returned a list of content
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - filename
                    - timestampMs
                  properties:
                    filename:
                      type: string
                    timestampMs:
                      type: integer
                    size:
                      type: integer
        '408': # used for esp32 that doesn't support 429
          description: Too Many Requests (try again)
        '429':
          description: Too Many Requests (try again)

  /catalog/{filename}:
    parameters:
      - name: filename
        in: path
        required: true
        schema:
          type: string
    get:
      description: receive the file
      responses:
        '200':
          description: transferring file
          headers:
            X-FileTimestamp-MS:
              schema:
                type: integer
          content:
             application/octet-stream: {}
        '404':
          description: File Not Found
        '408': # used for esp32 that doesn't support 429
          description: Too Many Requests (try again)
        '429':
          description: Too Many Requests (try again)
    put:
      description: add file
      parameters:
        - in: query
          name: timestamp_ms
          schema:
            type: integer
          required: true
      requestBody:
        content:
          # must set HTTP:Content-Length
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: accepted file
        '404':
          description: Illegal file name
        '411':
          description: Content-Length required
        '408': # used for esp32 that doesn't support 429
          description: Too Many Requests (try again)
        '429':
          description: Too Many Requests (try again)
    delete:
      description: remove file
      responses:
        '200':
          description: file was removed
        '404':
          description: File Not Found

  /firmware:
    get:
      description: Returns current firmware info
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                required:
                  - filename
                  - version
                properties:
                  filename:
                    type: string
                  version:
                    type: string
        '408': # used for esp32 that doesn't support 429
          description: Too Many Requests (try again)
        '429':
          description: Too Many Requests (try again)
        '500':
          description: invalid firmware
    put:
      description: update the firmware
      requestBody:
        content:
          # must set HTTP:Content-Length
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: accepted update, rebooting...
        '400':
          description: firmware was rejected
