openapi: 3.0.0
info:
  title: SneakerNet
  description: REST API for SneakerNet
  version: 0.0.0

servers:
  - url: http://sneakernet/

paths:
  /ebooks:
    get:
      summary: Catalog of EPUB3 ebooks {PublisherUUID:[ContentUUID]}
      responses:
        '200':
          description: OK
          content:
            applicaction/json:
              schema:
                type: object


  /ebooks/{publisherUuid}/{contentUuid}:
    parameters:
      - name: publisherUuid
        description: publisher's UUID
        in: path
        required: true
        schema:
          type: string
      - name: contentUuid
        description: content's UUID
        in: path
        required: true
        schema:
          type: string

    get:
      summary: Download EPUB3 ebook
      responses:
        '200':
          description: content
          content:
            application/epub+zip: {}

  /ebook:
    put:
      summary: Add EPUB3 ebook
      requestBody:
        required: true
        content:
          application/epub+zip: {}
      responses:
        '403':
          description: Librarian doesn't accept Publisher
        '406':
          description: epub book failed checks
        '415':
          description: epub format not supported
        '507':
          description: no more storage available on node

  /publishers/{publisher}:
    parameters:
      - name: publisher
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Publisher Info
      responses:
        '200':
          description: content
          content:
            application/xml:
              schema:
                $ref: 'http://www.w3.org/2000/09/xmldsig'

# [OPTIONAL] for SneakerNet nodes compiled with SNEAKERNET_FILES_SUPPORT
  /files:
    get:
      summary: Listing of stored files
      responses:
        '200':
          description: OK
          content:
            applicaction/json:
              schema:
                type: array

  /files/{filename}:
    put:
      summary: Add/Replace file
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/octet-stream: {}
      responses:
        '403':
          description: Librarian doesn't allow uncontrolled files
        '507':
          description: no more storage available on node
    delete:
      summary: Remove file
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: File removed
