openapi: 3.0.0
info:
  title: SneakerNet Librarian
  description: REST API for SneakerNet Librarian
  version: 0.0.0

servers:
  - url: http://192.168.1.1

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

    BearerAuth:
      type: http
      scheme: bearer

    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

paths:
  /publisher/{publisher}:
    parameters:
      - name: publisher
        description: publisher UID
        in: path
        required: true
        schema:
          type: integer
    put:
      summary: Add Publisher
      requestBody:
        description: Publisher info
        required: true
        content:
          application/xml:
            schema:
              $ref: 'http://www.w3.org/2000/09/xmldsig'
      responses:
        '507':
          description: no more storage available on node
    delete:
      summary: Remove Publisher
      responses:
        '200':
          description: OK

  /catalog/{publisher}/{content}:
    parameters:
      - name: publisher
        description: publisher's UID
        in: path
        required: true
        schema:
          type: integer
      - name: content
        description: content's UID
        in: path
        required: true
        schema:
          type: integer

    delete:
      summary: Remove EPUB3 ebook
      responses:
        '200':
          description: ebook was removed


# TODO change password
# TODO transfer ownership