name: sneakernet
description: SneakerNet App
publish_to: 'none'

version: 1.0.0+10

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_autostart: ^0.0.2
  flutter_foreground_task: ^6.2.0
#  workmanager: ^0.5.2

  permission_handler: ^11.0.1

  shared_preferences: ^2.1.2
  settings_ui: ^2.0.2
  multi_select_flutter: ^4.1.3

  wifi_scan: ^0.4.1
  wifi_iot: ^0.3.19

  openapi_generator_annotations: ^4.11.0
  sneakernet_rest:
    path: lib/rest
  version: ^3.0.2

  flutter_file_dialog: ^3.0.1
  path_provider: ^2.0.15
  share_plus: ^9.0.0
  ebook:
    git: https://github.com/redengin/dart-ebook.git
  open_filex: ^4.3.2
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  # path bound to ^1.8.3 by flutter_test
  path: ^1.8.3
  flutter_lints: ^3.0.1

  # REST API generator
  #   dart run build_runner build openapi_generator --delete-conflicting-outputs
  build_runner: ^2.4.6
  openapi_generator: ^4.11.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
     - firmware/esp32-sneakernet.bin
