name: sneakernet
description: SneakerNet App
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.0.1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  settings_ui: ^2.0.2
  shared_preferences: ^2.1.2

  auto_start_flutter: ^0.1.1
  permission_handler: ^10.3.0
  wifi_scan: ^0.4.0
  flutter_local_notifications: ^14.1.1
  workmanager: ^0.5.1
  plugin_wifi_connect: # ^1.0.2 FIXME published version doesn't match repos
    git:
      #      url: https://github.com/CadisRaziel/plugin_wifi_connect.git
      url: https://github.com/redengin/plugin_wifi_connect.git
      ref: redengin-patch-1
  openapi_generator_annotations: ^4.11.0
  sneakernet_rest:
    path: lib/rest
  version: ^3.0.2

  flutter_file_dialog: ^3.0.1
  path_provider: ^2.0.15
  path: ^1.8.3
  share: ^2.0.4
  ebook:
    git: https://github.com/redengin/dart-ebook.git
  open_filex: ^4.3.2
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # REST API generator
  #   dart run build_runner build openapi_generator --delete-conflicting-outputs
  build_runner: ^2.4.6
  openapi_generator: ^4.11.0

  # Generate launcher icons
  #     dart run flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1
  multi_select_flutter: ^4.1.3

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
     - firmware/esp32-sneakernet.bin
