[package]
name    = "sneakernet"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
# embassy-time    = "0.4.0"
# embassy-net     = { version = "0.6.0", features = [ "tcp", "udp", "dhcpv4", "medium-ethernet"] }
# heapless        = { version = "0.8.0", default-features = false, features = [ "portable-atomic", ] }