[package]
name    = "sneakernet"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
# static_cell      = { version = "2.1.0", features = ["nightly"] }
static_cell = "2.1.0"
# heapless         = { version = "0.8.0", default-features = false, features = [ "portable-atomic", ] }
heapless = "0.8.0"

embassy-executor = "0.7.0"
embassy-net      = { version = "0.6.0", features = [ "tcp", "udp", "dhcpv4", "medium-ethernet"] }

# embassy-time    = "0.4.0"