[env]
ESP_LOG = "sneakernet=debug"
WIFI_MAX_CHANNEL = "11"   # North America 11 / Others 13

[build]
target = "xtensa-esp32-none-elf"
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

[unstable]
build-std = ["alloc", "core"]

[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32 --baud 460800"
