[target.'cfg(target_arch = "riscv32")']
runner = "espflash flash --monitor"
rustflags = [
  "-C", "force-frame-pointers",
]

[target.'cfg(target_arch = "xtensa")']
runner = "espflash flash --monitor"
rustflags = [
  "-C", "force-frame-pointers",
  "-C", "link-arg=-nostartfiles",
]

[env]
ESP_LOGLEVEL = "info"

[build]
# target = "xtensa-esp8266-none-elf"
# target = "xtensa-esp32-none-elf"
# target = "xtensa-esp32s2-none-elf"
target = "xtensa-esp32s3-none-elf"


[unstable]
# build-std = ["alloc", "core"]
build-std = ["core"]