# Docker support for webapp development
services:
  angular:
    build:
      target: angular-cli
    tty: true
    user: ${DOCKER_USER:?set environment variable}
    environment:
      HOME : /home/angular
    volumes:
      - ~/.npm:/home/angular/.npm
      - ./angular:/home/angular/project
    working_dir: /home/angular/project

  ng-serve:
    build:
      target: angular-cli
    user: ${DOCKER_USER:?set environment variable}
    network_mode: host
    tty: true
    volumes:
      - ~/.npm:/home/angular/.npm
      - ./angular:/home/angular/project
    working_dir: /home/angular/project
    command: ng serve
    depends_on:
      - json-server

  json-server:
    build:
      target: json-server
    volumes:
      - ./angular:/home/angular/project
    working_dir: /home/angular/project
    init: true  # support CTRL-C stop
    command: json-server dev-db.json