# Docker support for webapp development
services:
  ng:
    build:
      target: angular-cli
    tty: true
    user: ${DOCKER_USER:?set environment variable}
    environment:
      HOME : /home/angular
    volumes:
      - ~/.npm:/home/angular/.npm
      - ./angular:/home/angular/project
    working_dir: /home/angular/project

  ng-serve:
    build:
      target: angular-cli
    user: ${DOCKER_USER:?set environment variable}
    network_mode: host # FIXME mapping ports doesn't work currently
    ports:
      - "4200:4200"
    tty: true
    volumes:
      - ~/.npm:/home/angular/.npm
      - ./angular:/home/angular/project
    working_dir: /home/angular/project
    command: ng serve
    init: true  # support CTRL-C stop
    depends_on:
      - json-server

  json-server:
    build:
      target: json-server
    network_mode: host # FIXME mapping ports doesn't work currently
    ports:
      - "3000:3000"
    volumes:
      - ./rest-fake.json:/rest-fake.json:ro
    init: true  # support CTRL-C stop
    command: json-server /rest-fake.json